sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.177.135
    port: 44244
    database: sky_take_out
    username: docker_mysql
    password: "00000000"

  minio:
    endpoint: http://192.168.177.135:49007 #Minio服务所在地址
    access-key: cangqiongwaimai #访问的key
    secret-key: "OfqlTh1bcw1QUKLc87fC0chgZdU2qG9T5TYtdkQF" #访问的秘钥
    bucket-name-dish: cqwm-dish #存储桶名称
    expire-time: 5 # 预签名url的过期时间（分钟）
